bridges:
  # Bridge for robot description
  - ros_topic_name: "/robot_description"
    gz_topic_name: "/robot_description"
    ros_type_name: "std_msgs/msg/String"
    gz_type_name: "gz.msgs.StringMsg"
    direction: "ROS_TO_GZ"

  # Bridge for spawn entity service
  - ros_topic_name: "/spawn_entity"
    gz_topic_name: "/world/empty/create"
    ros_type_name: "gazebo_msgs/srv/SpawnEntity"
    gz_type_name: "gz.msgs.EntityFactory"
    direction: "ROS_TO_GZ"

  # Bridge for joint states
  - ros_topic_name: "/joint_states"
    gz_topic_name: "/world/empty/model/docky/joint_state"
    ros_type_name: "sensor_msgs/msg/JointState"
    gz_type_name: "gz.msgs.Model"
    direction: "GZ_TO_ROS"

  # Bridge for TF
  - ros_topic_name: "/tf"
    gz_topic_name: "/world/empty/model/docky/tf"
    ros_type_name: "tf2_msgs/msg/TFMessage"
    gz_type_name: "gz.msgs.Pose_V"
    direction: "GZ_TO_ROS" 