services:
  jazzy:
    build: .
    container_name: jazzy
    volumes:
      - ../main_ws:/main_ws
    environment:
      - ROS_DOMAIN_ID=0
      - ROS_LOCALHOST_ONLY=0
      - DISPLAY=novnc:0
    networks:
      - x11
    privileged: true
    stdin_open: true
    tty: true
    working_dir: /main_ws
    restart: unless-stopped
    depends_on:
      - novnc

  novnc:
    image: theasp/novnc:latest
    container_name: novnc
    environment:
      - DISPLAY_WIDTH=1600
      - DISPLAY_HEIGHT=960
      - RUN_XTERM=no
    ports:
      - "8080:8080"
    networks:
      - x11

networks:
  x11:
    name: x11
    driver: host 