services:
  jazzy:
    build: .
    container_name: jazzy
    volumes:
      - ../main_ws:/main_ws
      - ../ros2_control_demos_ws:/ros2_control_demos_ws
    environment:
      - ROS_DOMAIN_ID=0
      - ROS_LOCALHOST_ONLY=0
      - DISPLAY=novnc:0
    # network_mode: host
    networks:
      - internal
    privileged: true
    stdin_open: true
    tty: true
    working_dir: /main_ws
    restart: unless-stopped

  novnc:
    image: theasp/novnc:latest
    container_name: novnc
    environment:
      - DISPLAY_WIDTH=1920
      - DISPLAY_HEIGHT=1080
      - RUN_XTERM=no
    networks:
      - internal # noVNC only works with docker custom network
    ports:
      - "8080:8080"

networks:
  internal:
    name: internal # use host.docker.internal for host network